// Generated by https://quicktype.io

package com.modyo.pokemon.api.entities;

import com.fasterxml.jackson.annotation.*;

public class GenerationV {
    private Sprites blackWhite;

    @JsonProperty("black-white")
    public Sprites getBlackWhite() { return blackWhite; }
    @JsonProperty("black-white")
    public void setBlackWhite(Sprites value) { this.blackWhite = value; }
}
