// Generated by https://quicktype.io

package com.modyo.pokemon.api.entities;

import com.fasterxml.jackson.annotation.*;

public class OfficialArtwork {
    private String frontDefault;

    @JsonProperty("front_default")
    public String getFrontDefault() { return frontDefault; }
    @JsonProperty("front_default")
    public void setFrontDefault(String value) { this.frontDefault = value; }
}
