// Generated by https://quicktype.io

package com.modyo.pokemon.api.entities;

import java.util.List;

import com.fasterxml.jackson.annotation.*;

public class Pokemon {

	
    
    private long count;
    private String next;
    private Object previous;
    private List<SmallPokemon> results;
    
    @JsonProperty("count")
    public long getCount() { return count; }
    @JsonProperty("count")
    public void setCount(long value) { this.count = value; }

    @JsonProperty("next")
    public String getNext() { return next; }
    @JsonProperty("next")
    public void setNext(String value) { this.next = value; }
    
    
    @JsonProperty("previous")
    public Object getPrevious() { return previous; }
    @JsonProperty("previous")
    public void setPrevious(Object value) { this.previous = value; }

    @JsonProperty("results")
    public List<SmallPokemon> getResults() { return results; }
    @JsonProperty("results")
    public void setResults(List<SmallPokemon> value) { this.results = value; }
    
}
