// Generated by https://quicktype.io

package com.modyo.pokemon.api.entities;

import com.fasterxml.jackson.annotation.*;

public class SmallPokemon {
	
    private String name;
    private String url; 
    private PokemonInfo info;    
    
    @JsonProperty("name")
    public String getName() { return name; }
    @JsonProperty("name")
    public void setName(String value) { this.name = value; }

    @JsonProperty("url")
    public String getURL() { return url; }
    @JsonProperty("url")
    public void setURL(String value) { this.url = value; }
    
    @JsonProperty("pokemoninfo")
    public PokemonInfo getPokemonInfo() { return info; }
    @JsonProperty("pokemoninfo")
    public void setPokemonInfo(PokemonInfo value) { this.info = value; }
    
    
    @JsonProperty("id")
    public Long getID() { 
    	try {
    		String path = this.getURL().substring(0, this.getURL().length()-1);
    		String str = path.substring(path.lastIndexOf("/")+1);
		    return Long.valueOf(str);
		}
    	catch (Exception e) {
		    return 0l;
		}
     	
    }
    
    @JsonProperty("img")
    public String getImg() { return "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/" + this.getID() + ".svg"; }
    

}